#!/bin/bash
# Copy current directory to middle-click clipboard
# --win: Use windows directory



if [ "$1" == "win" -o "$1" == "--win" -o "$1" == "-w" ]; then
  # Copy windows path
  TXT="$(cygpath --windows "$PWD")"
else
  # Copy Unix path
  TXT="$PWD"
fi

echo -n "$TXT" | xclip -selection primary

echo "Put to middle-click clipoard:"
echo "$TXT"
