#!/bin/bash
# Copy complete file name to middle-click clipboard
# --win: Use windows directory

USEWIN=0
if [ "$1" == "win" -o "$1" == "--win" -o "$1" == "-w" ]; then
  # Use windows path instead
  USEWIN=1
  shift
fi

# Also special handling of "\ " --> " " otherwise you cannot paste it into GUI
# programs
INFILE="${1//\\ / }"

echo "$INFILE"


if [ -z "$INFILE" ]; then
   echo "Copy complete file name to middle-click clipboard"
   echo "call with $0 [--win] filename"
fi

if [ $USEWIN -eq 1 ]; then
  # Use windows path instead
  INFILE="$(cygpath --windows "$INFILE")"
else
   # Canonialize INFILE
   if [[ ${INFILE} == */* ]]; then
      # Take care when we are not in current directory - but this resolved links
      # (not always wanted)
      INFILE=$(readlink -m "${INFILE}")
   else
      INFILE="${PWD}/${INFILE}"
   fi
fi


if [ "${OS}" == "Windows_NT" ]; then
  # Cygwin
  echo -n "$INFILE" | putclip
else
  # Linux
  echo -n "$INFILE" | xclip -selection primary
fi

echo "Put to middle-click clipoard:"
echo "$INFILE"
