#!/bin/bash
# Wrapper for gnupg2's dirmngr (gpg keyserver access daemon) to kill itself after 1 min.
# Otherwise it will linger forever around in memory, which I don't like.
#
# Enable in ~/.gnupg/gpg.conf:
# dirmngr-program PREFIX/dirmngr-wrapper


# Settings
# Timeout in seconds
TIME_END=60
# Debug: 10 seconds
# TIME_END=10
# Dirmngr command
DIRMNGR_CMD=dirmngr

# Debug output
# xmessage dirmngr "$@" &

# Now start dirmngr with all supplied options
$DIRMNGR_CMD "$@" &

# Wait in subprocess, to not block caller
( sleep $TIME_END

# Now kill it when still running
if [[ $(pgrep -c $DIRMNGR_CMD) ]]; then
   # Debug output
   # xmessage  $0: Time is up - Killing dirmngr
   gpgconf --kill $DIRMNGR_CMD
fi
) &
