#!/bin/bash
#
# git Wrapper for (my) commonly used command, which I do not remember
#
#  (c) by Robert Lange (robert.lange@s1999.tu-chemnitz.de)
#  GNU General Public Licence applies


case "$1" in
   loggraph)
      shift
      echo git log --pretty=format:'%h %s' --graph "$@"
      git log --pretty=format:'%h %s' --graph "$@"
      echo
      ;;
   logfiles)
      shift
      if [ "$1" == "-v" ]; then
	  shift
	  echo git log --stat "$@"
	  git log --stat "$@"
      else
	  echo git log --name-status "$@"
	  git log --name-status "$@"
      fi
      ;;
   *) echo Unknown action \"$1\"!
      echo
      echo "Git: Wrapper around command line git for my common used command"
      echo "which I do not remember."
      echo "Action to perform is determined by first argument, following arguments"
      echo "are just handed over to git"
      echo "Sometimes a second modifier is supported, see following list"
      echo
      echo "Actions"
      echo "*******"
      echo "loggraph: Show shorted log as graph"
      echo "logfiles: Log output with changed files (-v: More details)"
      echo
      ;;
esac
