#!/bin/bash
# Wrapper for gnupg2's gpg-agent (gpg secret key handling daemon) to kill itself after 30 min.
# Otherwise it will linger forever around in memory, which I don't like.
#
# Enable in ~/.gnupg/gpg.conf:
# agent-program PREFIX/gpg-agent-wrapper


# Settings
# Timeout in seconds
TIME_END=1800
# Debug: 30 seconds
# TIME_END=30
# Agent command
AGENT_CMD=gpg-agent

# Debug output (non-blocking)
# xmessage $AGENT_CMD "$@" &

# Now start gpg-agent with all supplied options
$AGENT_CMD "$@" &

# Wait
sleep $TIME_END

# Now kill it when still running
if [[ $(pgrep -c $AGENT_CMD) ]]; then
   # Debug output (blocking)
   # xmessage  $0: Time is up - Killing gpg-agent
   gpgconf --kill gpg-agent
fi
