#!/bin/bash
# Re-encode movies taken from digital cameras to significantly shrink the file size
# with only a small loss of quality.
# Resutling files are in MPEG4 format, the bitrate is determined by the input
# movie width. Please modify/add in the file your favourite values.
# It uses two pass encoding.
#
#      Version: $LastChangedRevision$
#  last change: $LastChangedDate: 2008-03-21 22:36:35 +0100 (Fri, 21 Mar 2008) $
#
#    Copyright (C) 2013,2014 by Robert Lange <sd2k9@sethdepot.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# ------------------------------------------------------------------------------

# *** Settings ***
# Mencoder
MENCODER=mpv
# Encoding options are set below
# Movie Identification - use script from mpv
MIDENTIFY="midentify"
# Number of threads to use for encoding
# Default use number of processors in system
THREADS=$(grep "processor" /proc/cpuinfo | wc -l)

# ------------------------------------------------------------------------------
# *** Functions ***
function help_text() {
cat<<EOF
Shrink (camera) videos to smaller size

Usage: $(basename $0) [--start starttime] [--end endtime] model inputfile outputfile.mp4

--start starttime: Start encoding from time, in seconds or hh:mm:ss
--end endtime:     Finish encoding at time,  in seconds or hh:mm:ss
model: Bitrate presets for encoding
       ACTIONPRO: Actionpro X7 camera
       IXUS500: Canon Ixus 500
       VHS: VHS Mono PAL Video

inputfile: File to shrink
outputfile.mp4: Resulting file, Format is MP4

Used commands: $MENCODER $MPLAYER

EOF
}

# Print Versionstring
function versionstring () {
# REVISION='$LastChangedRevision$'
# REVISION=${REVISION#\$LastChangedRevision: }
# REVISION=${REVISION% \$}
cat<<EOF
shrink-vids, Revision DEV
(c) 2013,2014 by Robert Lange (sd2k9@sethdepot.org)
Licensed under the GNU General Public License

EOF
}

# TODO: MPV does not require parsing anymore, doesn't it? So remove this also
# Parse time to seconds
# Input: ss oder hh:mm:ss
function parse_time() {
    local num
    num="$1"
    shift

    # Only numbers? Return as-is
    if [[ $num =~ ^[0-9]+$ ]] ; then
	echo "$num"

    # hh:mm:ss? Let date do the work
    elif [[ $num =~ ^[0-2][0-9]:[0-5][0-9]:[0-5][0-9]$ ]] ; then
	echo $(date -u --date "1970-01-01 ${num}"  +"%s")
    # Everything else? Error
    else
	echo "Error: Unknown time format ${num}" 1>&2;  # To stderr, otherwise its caught as return
	echo ""
    fi
}


# ------------------------------------------------------------------------------

# *** Rudimentary command line parsing

# *** Kommandozeile auswerten
get_options() {
  local opt
  local argcounter=1

   # Parse command line for options
   while [ -n "$*" ]; do
      opt="$1"
      shift
      case $opt in
      --help | -h) # Help
         # First print  Versionstring
         versionstring
         echo
         help_text
         exit
         ;;
      --version | -V) # Version
         echo
         versionstring
         exit
         ;;
      --start | -ss) # Next argument: Start Time
         opt="$1"
         shift
         MOV_START=$(parse_time "$opt")
	 if [ -z "${MOV_START}" ]; then # Error occured
	     exit 1
	 fi
         ;;
      --end | -e) # Next argument: End time
         opt="$1"
         shift
         MOV_END=$(parse_time "$opt")
	 if [ -z "${MOV_END}" ]; then # Error occured
	     exit 1
	 fi
         ;;
      *) # Positional options
     	  case $argcounter in
      	    1)
      		MODEL="$opt"
      		;;
      	    2)
      		INFILE="$opt"
      		;;
      	    3)
      		OUTFILE="$opt"
      		;;
      	    *)
                # Too many arguments
  	        echo "Too many arguments! See help text for usage"
  		exit 1
  		;;
      	  esac
          #increment argument counter
          let argcounter++
          ;;
      esac
    done
}

# *** Call Command Line Parsing
# When no options supplied then call help
if [ -z "$1" ]; then
    get_options "--help"
else
    get_options "$@"
fi


# No or wrong commands supplied
if [ -z "$OUTFILE" ]; then
    echo "Wrong number of command line options!"
    echo
    help_text
    exit 1
fi

# *** Check for input file
if [ ! -f "$INFILE" ]; then
   echo "Input file \"$INFILE\" not existing!"
   exit 1
fi

# *** Check for output directory, first check is for current directory (returns filename as-is)
if [ "${OUTFILE}" != "${OUTFILE%/*}" -a ! -d "${OUTFILE%/*}" ]; then
   echo "Output directory \"${OUTFILE%/*}\" not existing!"
   exit 1
fi
# *** Check for output Extension: Options tweaked for mp4 so this must be selected
if [ "${OUTFILE##*.}" != "mp4" ]; then
   echo "Wrong output file extension \"${OUTFILE%/*}\"! Options are tweaked for mp4 output!"
   exit 1
fi

# ------------------------------------------------------------------------------

# *** Now execute the action

# *** Determine input material
VIDEO_WIDTH=$($MIDENTIFY "$INFILE" 2> /dev/null |grep "^width" | cut -c 7-)


# *** Set encoding options
# Additional encoder options
MENCODER_MOREOPTS=
# Descriptive text when used
MENCODER_MOREOPTS_DESC=
# Select appropriate bitrate
# IXUS500: This is for Canon Ixus 500
case ${MODEL} in
 "actionpro"|"ACTIONPRO"|"X7"|"x7")
  # Actioncam Actionpro X7
  case ${VIDEO_WIDTH} in
   1920)
     echo "UPDATE VIDEO BITRATE FOR MENCODER->MPV, RECOMMENDED START IS shr 1"
     exit
     VIDEO_BITRATE=12000k
     AUDIO_BITRATE=64k
     ;;
   1280)
     echo "UPDATE VIDEO BITRATE FOR MENCODER->MPV, RECOMMENDED START IS shr 1"
     exit
     VIDEO_BITRATE=6000k
     AUDIO_BITRATE=64k
     ;;
   *)
     echo "Unknown Input Video Material - Movie Width is ${VIDEO_WIDTH}"
     echo "Dunno how to setup video bit rate - Exiting"
     exit
     ;;
  esac
  ;;
 "ixus500"|"IXUS500"|"ixus"|"IXUS")
  # For Canon Ixus 500
  case ${VIDEO_WIDTH} in
   1920)
     echo "UPDATE VIDEO BITRATE FOR MENCODER->MPV, RECOMMENDED START IS shr 1"
     exit
     VIDEO_BITRATE=5000k
     AUDIO_BITRATE=56k
     ;;
   640)
     VIDEO_BITRATE=640k
     AUDIO_BITRATE=56k
     ;;
   *)
     echo "Unknown Input Video Material - Movie Width is ${VIDEO_WIDTH}"
     echo "Dunno how to setup video bit rate - Exiting"
     exit
     ;;
  esac
  ;;
 "VHS"|"vhs")
  # For VHS Video PAL Mono Encoding
  VIDEO_BITRATE=768k
  AUDIO_BITRATE=56k
  # Cropping and Noise Filtering - Deinterlacing disabled
  # mencoder MENCODER_MOREOPTS="${MENCODER_MOREOPTS} -vf crop=696:552:12:8,denoise3d -noslices"
  MENCODER_MOREOPTS="${MENCODER_MOREOPTS} --vf crop=696:552:12:8,hqdn3d"
  if [ -n "${MENCODER_MOREOPTS_DESC}" ]; then  # Add space and komma
      MENCODER_MOREOPTS_DESC="${MENCODER_MOREOPTS_DESC}, "
  fi
  # MENCODER_MOREOPTS_DESC="${MENCODER_MOREOPTS_DESC}Cropping and Deinterlacing"
  MENCODER_MOREOPTS_DESC="${MENCODER_MOREOPTS_DESC}Cropping and Denoising"
  ;;
 *)
   echo "Unknown Video Type (Model) - Exiting"
   exit
   ;;
esac


# *** Now bild start and end time, when requested
# Start time we can take verbatim
if [ -n "${MOV_START}" ]; then
   # Now build the options
   MENCODER_MOREOPTS="${MENCODER_MOREOPTS} --start ${MOV_START}"
   # Update desc text
   if [ -n "${MENCODER_MOREOPTS_DESC}" ]; then  # Add space and komma
         MENCODER_MOREOPTS_DESC="${MENCODER_MOREOPTS_DESC}, "
   fi
   MENCODER_MOREOPTS_DESC="${MENCODER_MOREOPTS_DESC}Start Time"

   # Both start and endtime are given
   # TODO: For mpv no distinction is required because of native --end parameter -> Simplify
   if [ -n "${MOV_END}" ]; then
      # Is start smaller than end
      if [ ${MOV_START} -ge ${MOV_END} ]; then
          echo "ERROR: start must be smaller than end! You wanna encode backwards?!"
          exit 1
      fi
      # Now also build end time
      # mencoder MENCODER_MOREOPTS="${MENCODER_MOREOPTS} -endpos $((${MOV_END} - ${MOV_START}))"
      MENCODER_MOREOPTS="${MENCODER_MOREOPTS} --end ${MOV_END}"
      # Update desc text
      if [ -n "${MENCODER_MOREOPTS_DESC}" ]; then  # Add space and komma
            MENCODER_MOREOPTS_DESC="${MENCODER_MOREOPTS_DESC}, "
      fi
      MENCODER_MOREOPTS_DESC="${MENCODER_MOREOPTS_DESC}End Time"
   fi
fi
# Only end time given, no start
if [ -n "${MOV_END}" -a -z "${MOV_START}" ]; then
   # Can take end time verbatim
   MENCODER_MOREOPTS="${MENCODER_MOREOPTS} --end ${MOV_END}"
   # Update desc text
   if [ -n "${MENCODER_MOREOPTS_DESC}" ]; then  # Add space and komma
         MENCODER_MOREOPTS_DESC="${MENCODER_MOREOPTS_DESC}, "
   fi
   MENCODER_MOREOPTS_DESC="${MENCODER_MOREOPTS_DESC}End Time"
fi


# Mencoder default options; taken from www.mplayerhq.hu and
# a little bit adjusted. I am sure there is much space for improvement.
# No audio resampling: -srate 22050
# Two pass encoding is appended at the end
# "-noskip -mc 0" is recommended but sometimes leads to a/v desync - thus removed
# mencoder MENCODER_OPTS="${MENCODER_MOREOPTS} \
#     -oac mp3lame -lameopts q=0:aq=0:abr:br=${AUDIO_BITRATE}:mode=3 \
#     -ovc lavc -lavcopts \
#     vcodec=mpeg4:vbitrate=${VIDEO_BITRATE}:mbd=1:mv0:trell:v4mv:cbp:last_pred=3:predia=2:dia=2:vmax_b_frames=2:vb_strategy=1:precmp=2:cmp=2:subcmp=2:preme=2:qns=2:threads=${THREADS}"
# TODO: Use mpv's *opts-add for 1/2-pass option
# Use libvorbis instead of mp3 for audio encoding
MENCODER_OPTS_PASS1="${MENCODER_MOREOPTS} \
    --ovc libx264 --ovcopts b=${VIDEO_BITRATE},threads=${THREADS},preset=veryslow,trellis=1,fastfirstpass=1,flags=+pass1 \
    --audio-channels mono --oac libvorbis --oacopts b=${AUDIO_BITRATE},flags=+pass1"
MENCODER_OPTS_PASS2="${MENCODER_MOREOPTS} \
    --ovc libx264 --ovcopts b=${VIDEO_BITRATE},threads=${THREADS},preset=veryslow,trellis=1,flags=+pass2 \
    --audio-channels mono --oac libvorbis --oacopts b=${AUDIO_BITRATE},flags=+pass2"

# *** Execute shrink ***
echo
echo "Converting file ..."
echo "Selected Coding Model = ${MODEL}"
echo "Selected bitrate = ${VIDEO_BITRATE}bps"
echo "Selected Audio Bitrate = ${AUDIO_BITRATE}bps"
if [ -n "${MENCODER_MOREOPTS_DESC}" ]; then
   echo "Additional Encoding Options = ${MENCODER_MOREOPTS_DESC}"
fi
if [ -n "${MOV_START}" -o -n "${MOV_END}" ]; then
   echo "Only encode from ${MOV_START}s to ${MOV_END}s"
fi
echo "First pass ..."
echo $MENCODER ${MENCODER_OPTS_PASS1} -o $OUTFILE $INFILE
$MENCODER ${MENCODER_OPTS_PASS1} -o "$OUTFILE" "$INFILE"
echo "Second pass ..."
echo $MENCODER ${MENCODER_OPTS_PASS2} -o $OUTFILE $INFILE
$MENCODER ${MENCODER_OPTS_PASS2} -o "$OUTFILE" "$INFILE"

# Error when result file was not created
if [ ! -f "$OUTFILE" ]; then
  echo "Result file not existing! Something went wrong"
  exit 1
fi

# Remove statistics files again
rm x264_2pass.log x264_2pass.log.mbtree
rm "${OUTFILE}-vo-lavc-pass1.log"

# *** Print resulting file size ***
echo
echo "File sizes:"
ls -1 -hs "$INFILE" "$OUTFILE"
echo

