#!/usr/bin/env python3
# Starts a program minimized
# Original Source: https://askubuntu.com/questions/663187/how-can-i-run-a-program-on-startup-minimized
#
# Needs: wmctrl, pgrep, xdotool
#
# 1.P: Program name
# 2+.P: Program arguments

#!/usr/bin/env python3
import subprocess
import sys
import time

# Basic command line check
if len(sys.argv) == 1 or sys.argv[1] == "-h" or sys.argv[1] == "--help":
    print("start_minimized: Starts a program minimized")
    print("Original Source: https://askubuntu.com/questions/663187/how-can-i-run-a-program-on-startup-minimized")
    print("\nUsage:")
    print("start_minimized program [arguments ...]")
    sys.exit()
trackfil = sys.argv[1]


# The action starts here
command = sys.argv[1]
command_check = command.split("/")[-1]

subprocess.Popen(["/bin/sh", "-c", command])

t = 1
while t < 30:
    try:
        w_list = [l.split() for l in subprocess.check_output(["wmctrl", "-lp"]).decode("utf-8").splitlines()]
        proc = subprocess.check_output(["pgrep", "-f", command_check]).decode("utf-8").strip().split()
        match = sum([[l[0] for l in w_list if p in l] for p in proc], [])
        subprocess.Popen(["xdotool", "windowminimize", match[0]])
        break
    except (IndexError, subprocess.CalledProcessError):
        pass
    t += 1
    time.sleep(1)
