#!/bin/bash
#
# Script to keep xscreensaver inactive, and also kill/resume another process at the same time.

# Reasonable DELAY to keep xscreensaver from activating
readonly DELAY=1m

# Programm to kill/resume
readonly KILL_PROG=workrave

echo "Killing $KILL_PROG ..."
pkill -u $USER $KILL_PROG

# Installing trap to restart program
trap "($KILL_PROG &); exit" SIGINT

echo "Keeping screensaver from activation ..."
echo "Abort with Ctrl+C"

while true
do
        xscreensaver-command --deactivate
        sleep $DELAY
done

